### ISSUE TITLE
Cannot find the File camunda.mk

### ISSUE THREAD

**Issue by javakasper** [camunda-community-hub/camunda8-greenfield-installation#2]
# Camunda Community Hub Pull Request Template

## Description

The Path Makefile:46: ../../camunda-8-helm-profiles/include/camunda.mk: No such file or directory is not exist.  The Link to [Camunda 8 Helm Profiles git repository] throws to (https://github.com/camunda-community-hub/zeebe-helm-profiles).
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an existing open issue)
- [ ] New feature (non-breaking change which adds functionality to an extension)
- [ ] Breaking change (fix or feature that would cause existing functionality of an extension to change)
- [ ] Documentation update (changes made to an existing piece of documentation)

## Checklist:

- [ ] My code adheres to the syntax used by this extension.
- [ ] My pull request requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **Camunda Community Hub** documentation
- [ ] I have read the **Pull Request Process** documentation
- [ ] I have added or suggested tests to cover my changes suggested in this pull request.
- [ ] All new and existing CI/CD tests passed.
- [ ] I will /assign myself this issue, and add the relevant [issue labels] to it if they are not automatically generated by Probot.
- [ ] I will tag @camunda-community-hub/devrel in a new comment on this issue if 30 days have passed since my pull request was opened and I have not received a response from the extension's Maintainer

**Comment by upgradingdave** [comment]
Thanks for the report @javakasper!

Sorry for the confusion, we're in the process or organizing and renaming repositories. In the meantime, I updated the link in the README so that the directory is created as `camunda-8-helm-profiles` instead of `zeebe-helm-profiles` (47c8b6a1bbd7e6e3f942ebda95b1cb24ab2aed97)
