### ISSUE TITLE
Should k8s installation scripts be merged with the Helm profiles?

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda8-greenfield-installation#3]
[Some](https://github.com/camunda-community-hub/zeebe-helm-profiles/pull/10#pullrequestreview-1075130785) [comments](https://github.com/camunda-community-hub/zeebe-helm-profiles/pull/10#issuecomment-1218025737) [suggested](https://github.com/camunda/camunda-platform-helm/pull/373#issuecomment-1216648844) to merge the content of this repo with the [camunda-8-helm-profiles](https://github.com/camunda-community-hub/zeebe-helm-profiles).

FYI @Zelldon @aabouzaid @upgradingdave

**Comment by falko** [comment]
This really needs careful discussion. `greenfield` might be a bad name to start with as it reflects only part of the problem that this repo solves. The starting points of both repos are completely different: If I have nothing but a cloud account, I need to install k8s first and then Camunda. If I already have k8s, I only care about the right chart values for my use case and would look at [camunda-8-helm-profiles](https://github.com/camunda-community-hub/zeebe-helm-profiles), which should also point me to a "greenfield" recommendation of which profile to use depending on my environment. Maybe more important then how many repos or which folder structure we have would be to write good docs that guide people to the right entry point.

Actually, the ways to install k8s and the ways to install Camunda with Helm are rather orthogonal to each other, i.e. one can combine any K8s cluster with any Helm profile (except for some profiles dependencies on cloud provider specific infrastructure)

**Comment by falko** [comment]
See also the following comments:
- https://github.com/camunda/camunda-platform-helm/pull/373#issuecomment-1216434646
- https://github.com/camunda/camunda-platform-helm/pull/373#issuecomment-1217996054

**Comment by falko** [comment]
`greenfield` reflects the that the Camunda configuration will be opinionated.
What the name of the repo should also reflect is that it is primarily about installing Kubernetes in an otherwhise empty cloud account or on a developer's computer. The installation of Camunda is only for convenience and could also be excluded because that's what the Helm profiles solve.

**Comment by falko** [comment]
I added [a summary of what this repo provides](https://github.com/camunda-community-hub/camunda8-greenfield-installation/commit/452b68ec42cfeaf7e933ae2c9c34514d3e4fe0b3)

**Comment by falko** [comment]
Eating out own dog food, I added this decision table to the readme:
![decision table with installation options](https://github.com/camunda-community-hub/camunda8-greenfield-installation/raw/main/camunda-8-installation-options.png)

**Comment by falko** [comment]
Maybe a better name for this repo would be something like `kubernetes-installation-for-camunda-8` or `camunda-8-kubernetes-installation`.

**Comment by falko** [comment]
> Maybe a better name for this repo would be something like `kubernetes-installation-for-camunda-8` or `camunda-8-kubernetes-installation`.

@upgradingdave @plungu what do you think? Shall we rename this repo to `camunda-8-kubernetes-installation` in order to make it's purpose more clear?

**Comment by plungu** [comment]
The name change sounds reasonable to me.

Paul Lungu
E: ***@***.***
P: 303-520-6414
linkedin.com/in/plungu
github.com/plungu

**Comment by falko** [comment]
We are going to try merging this repo into https://github.com/camunda-community-hub/camunda-8-helm-profiles

See: https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/31

I'll try the same for GCP.

**Comment by falko** [comment]
PR for Google: https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/33

**Comment by upgradingdave** [comment]
Hi all, just fyi, I have some time to work this week to combine the greenfield repo into `camunda-8-helm-profiles`. 

As I work thru the tasks, I'll stage changes in [PR #36](https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/36)

Here's the (ambitious!) plan for the week: 

- [x] Create [an integration branch](https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/int-20221031). I plan to do all the following tasks inside this integration branch
- [x] Update main README.md
- [x] Move `metrics` from greenfield to [int-20221031](https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/int-20221031)
- [x] Add README for `metrics`
- [x] Merge common File changes [PR 30](https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/30) into [int-20221031](https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/int-20221031)
- [x] Merge Azure Profile [PR 31](https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/31) into [int-20221031](https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/int-20221031)
- [x] Update README for `azure`
- [x] Regression Test that Azure Profile works
- [x] Merge Google Profile, [PR 33](https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/33), into [int-20221031](https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/int-20221031)
- [x] update README for `google`
- [x] Regression Test that Google Profile works
- [x] Move AWS Profile from greenfield to Helm Profiles and Regression Test
- [x] Update README for `aws`
- [x] Merge Kind Profile, [PR 12](https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/12), into into [int-20221031](https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/int-20221031)
- [x] Update README for `Kind`
- [x] Test Kind Profile

If you have concerns / suggestions, please let me know!
Thanks,
Dave

**Comment by upgradingdave** [comment]
Everything has been moved over to Camunda 8 Helm profiles
