### ISSUE TITLE
Add metrics to all installations

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda8-greenfield-installation#7]
Prometheus and Grafana somehow got removed from the installation scripts. I already added it back to Google in 11016e68eb55820ef5a8e709b4a54b07abf8484d

**Comment by upgradingdave** [comment]
I added metrics to the AWS makefile in this commit: ae921d75ecf1aa253dde7d7603cac5537198dcc9. 

Tested and was able to access the Grafana dashboard. The AWS section in the README has been updated. 

Still need to add and test in Azure environment.

**Comment by upgradingdave** [comment]
As part of combining this repo with camunda-8-helm-profiles, metrics will be installed by default in the nginx ingress tls profiles for google, azure and aws.
